function escXml(str = '') {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Builds optional SVG overlay composition for brand-consistent text layer.
 * The base image itself is generated by AI and referenced by URL.
 *
 * @param {Object} params
 * @param {string} params.baseImageUrl
 * @param {number} params.width
 * @param {number} params.height
 * @param {string} [params.headline]
 * @param {string} [params.subline]
 * @returns {string}
 */
export function buildOverlaySvg({
  baseImageUrl,
  width,
  height,
  headline = '',
  subline = '',
}) {
  const safeHeadline = escXml(headline);
  const safeSubline = escXml(subline);
  const w = Number(width) || 1080;
  const h = Number(height) || 1080;
  const titleY = Math.max(96, Math.floor(h * 0.14));
  const sublineY = titleY + 68;

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
  <defs>
    <linearGradient id="ov" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="rgba(0,0,0,0.25)"/>
      <stop offset="100%" stop-color="rgba(0,0,0,0.48)"/>
    </linearGradient>
  </defs>
  <image href="${escXml(baseImageUrl)}" x="0" y="0" width="${w}" height="${h}" preserveAspectRatio="xMidYMid slice"/>
  <rect x="0" y="0" width="${w}" height="${h}" fill="url(#ov)"/>
  ${safeHeadline ? `<text x="64" y="${titleY}" fill="#F8F4EE" font-size="56" font-weight="600" font-family="'Cormorant Garamond', serif">${safeHeadline}</text>` : ''}
  ${safeSubline ? `<text x="64" y="${sublineY}" fill="#E7E0D4" font-size="28" font-family="'Montserrat', sans-serif">${safeSubline}</text>` : ''}
</svg>`;
}

